interface Country {
    code: string;
    flag: string;
    name: string;
}

export const countries: Country[] = [
    { code: "US", flag: "🇺🇸", name: "Stany Zjednoczone" },
    { code: "GB", flag: "🇬🇧", name: "Wielka Brytania" },
    { code: "PL", flag: "🇵🇱", name: "Polska" },
    { code: "FL", flag: "🇫🇮", name: "Finlandia" },
    { code: "AF", flag: "🇦🇫", name: "Afganistan" },
    { code: "AL", flag: "🇦🇱", name: "Albania" },
    { code: "DZ", flag: "🇩🇿", name: "Algieria" },
    { code: "AD", flag: "🇦🇩", name: "Andora" },
    { code: "AO", flag: "🇦🇴", name: "Angola" },
    { code: "AG", flag: "🇦🇬", name: "Antigua i Barbuda" },
    { code: "AR", flag: "🇦🇷", name: "Argentyna" },
    { code: "AM", flag: "🇦🇲", name: "Armenia" },
    { code: "AU", flag: "🇦🇺", name: "Australia" },
    { code: "AT", flag: "🇦🇹", name: "Austria" },
    { code: "AZ", flag: "🇦🇿", name: "Azerbejdżan" },
    { code: "BS", flag: "🇧🇸", name: "Bahamy" },
    { code: "BH", flag: "🇧🇭", name: "Bahrajn" },
    { code: "BD", flag: "🇧🇩", name: "Bangladesz" },
    { code: "BB", flag: "🇧🇧", name: "Barbados" },
    { code: "BE", flag: "🇧🇪", name: "Belgia" },
    { code: "BZ", flag: "🇧🇿", name: "Belize" },
    { code: "BJ", flag: "🇧🇯", name: "Benin" },
    { code: "BT", flag: "🇧🇹", name: "Bhutan" },
    { code: "BY", flag: "🇧🇾", name: "Białoruś" },
    { code: "BO", flag: "🇧🇴", name: "Boliwia" },
    { code: "BA", flag: "🇧🇦", name: "Bośnia i Hercegowina" },
    { code: "BW", flag: "🇧🇼", name: "Botswana" },
    { code: "BR", flag: "🇧🇷", name: "Brazylia" },
    { code: "BN", flag: "🇧🇳", name: "Brunei" },
    { code: "BG", flag: "🇧🇬", name: "Bułgaria" },
    { code: "BF", flag: "🇧🇫", name: "Burkina Faso" },
    { code: "BI", flag: "🇧🇮", name: "Burundi" },
    { code: "CV", flag: "🇨🇻", name: "Cabo Verde" },
    { code: "CL", flag: "🇨🇱", name: "Chile" },
    { code: "HR", flag: "🇭🇷", name: "Chorwacja" },
    { code: "TD", flag: "🇹🇩", name: "Czad" },
    { code: "ME", flag: "🇲🇪", name: "Czarnogóra" },
    { code: "CZ", flag: "🇨🇿", name: "Czechy" },
    { code: "DJ", flag: "🇩🇯", name: "Dżibuti" },
    { code: "DM", flag: "🇩🇲", name: "Dominika" },
    { code: "DO", flag: "🇩🇴", name: "Dominikana" },
    { code: "EG", flag: "🇪🇬", name: "Egipt" },
    { code: "EC", flag: "🇪🇨", name: "Ekwador" },
    { code: "ER", flag: "🇪🇷", name: "Erytrea" },
    { code: "EE", flag: "🇪🇪", name: "Estonia" },
    { code: "SZ", flag: "🇸🇿", name: "Eswatini" },
    { code: "ET", flag: "🇪🇹", name: "Etiopia" },
    { code: "FJ", flag: "🇫🇯", name: "Fidżi" },
    { code: "PH", flag: "🇵🇭", name: "Filipiny" },
    { code: "FI", flag: "🇫🇮", name: "Finlandia" },
    { code: "FR", flag: "🇫🇷", name: "Francja" },
    { code: "GA", flag: "🇬🇦", name: "Gabon" },
    { code: "GM", flag: "🇬🇲", name: "Gambia" },
    { code: "GH", flag: "🇬🇭", name: "Ghana" },
    { code: "GR", flag: "🇬🇷", name: "Grecja" },
    { code: "GD", flag: "🇬🇩", name: "Grenada" },
    { code: "GT", flag: "🇬🇹", name: "Gwatemala" },
    { code: "GW", flag: "🇬🇼", name: "Gwinea Bissau" },
    { code: "GN", flag: "🇬🇳", name: "Gwinea" },
    { code: "GY", flag: "🇬🇾", name: "Gujana" },
    { code: "HT", flag: "🇭🇹", name: "Haiti" },
    { code: "ES", flag: "🇪🇸", name: "Hiszpania" },
    { code: "HN", flag: "🇭🇳", name: "Honduras" },
    { code: "IN", flag: "🇮🇳", name: "Indie" },
    { code: "ID", flag: "🇮🇩", name: "Indonezja" },
    { code: "IQ", flag: "🇮🇶", name: "Irak" },
    { code: "IR", flag: "🇮🇷", name: "Iran" },
    { code: "IE", flag: "🇮🇪", name: "Irlandia" },
    { code: "IS", flag: "🇮🇸", name: "Islandia" },
    { code: "IL", flag: "🇮🇱", name: "Izrael" },
    { code: "JM", flag: "🇯🇲", name: "Jamajka" },
    { code: "JP", flag: "🇯🇵", name: "Japonia" },
    { code: "YE", flag: "🇾🇪", name: "Jemen" },
    { code: "JO", flag: "🇯🇴", name: "Jordania" },
    { code: "KH", flag: "🇰🇭", name: "Kambodża" },
    { code: "CM", flag: "🇨🇲", name: "Kamerun" },
    { code: "CA", flag: "🇨🇦", name: "Kanada" },
    { code: "QA", flag: "🇶🇦", name: "Katar" },
    { code: "KZ", flag: "🇰🇿", name: "Kazachstan" },
    { code: "KE", flag: "🇰🇪", name: "Kenia" },
    { code: "KG", flag: "🇰🇬", name: "Kirgistan" },
    { code: "KI", flag: "🇰🇮", name: "Kiribati" },
    { code: "CO", flag: "🇨🇴", name: "Kolumbia" },
    { code: "KM", flag: "🇰🇲", name: "Komory" },
    { code: "CG", flag: "🇨🇬", name: "Kongo" },
    { code: "CD", flag: "🇨🇩", name: "Kongo (DRK)" },
    { code: "KP", flag: "🇰🇵", name: "Korea Północna" },
    { code: "KR", flag: "🇰🇷", name: "Korea Południowa" },
    { code: "CR", flag: "🇨🇷", name: "Kostaryka" },
    { code: "CU", flag: "🇨🇺", name: "Kuba" },
    { code: "KW", flag: "🇰🇼", name: "Kuwejt" },
    { code: "LA", flag: "🇱🇦", name: "Laos" },
    { code: "LS", flag: "🇱🇸", name: "Lesotho" },
    { code: "LB", flag: "🇱🇧", name: "Liban" },
    { code: "LR", flag: "🇱🇷", name: "Liberia" },
    { code: "LY", flag: "🇱🇾", name: "Libia" },
    { code: "LI", flag: "🇱🇮", name: "Liechtenstein" },
    { code: "LT", flag: "🇱🇹", name: "Litwa" },
    { code: "LU", flag: "🇱🇺", name: "Luksemburg" },
    { code: "LV", flag: "🇱🇻", name: "Łotwa" },
    { code: "MK", flag: "🇲🇰", name: "Macedonia Północna" },
    { code: "MG", flag: "🇲🇬", name: "Madagaskar" },
    { code: "MW", flag: "🇲🇼", name: "Malawi" },
    { code: "MV", flag: "🇲🇻", name: "Malediwy" },
    { code: "MY", flag: "🇲🇾", name: "Malezja" },
    { code: "ML", flag: "🇲🇱", name: "Mali" },
    { code: "MT", flag: "🇲🇹", name: "Malta" },
    { code: "MA", flag: "🇲🇦", name: "Maroko" },
    { code: "MH", flag: "🇲🇭", name: "Wyspy Marshalla" },
    { code: "MR", flag: "🇲🇷", name: "Mauretania" },
    { code: "MU", flag: "🇲🇺", name: "Mauritius" },
    { code: "MX", flag: "🇲🇽", name: "Meksyk" },
    { code: "FM", flag: "🇫🇲", name: "Mikronezja" },
    { code: "MD", flag: "🇲🇩", name: "Mołdawia" },
    { code: "MN", flag: "🇲🇳", name: "Mongolia" },
    { code: "MZ", flag: "🇲🇿", name: "Mozambik" },
    { code: "NA", flag: "🇳🇦", name: "Namibia" },
    { code: "NR", flag: "🇳🇷", name: "Nauru" },
    { code: "NP", flag: "🇳🇵", name: "Nepal" },
    { code: "DE", flag: "🇩🇪", name: "Niemcy" },
    { code: "NE", flag: "🇳🇪", name: "Niger" },
    { code: "NG", flag: "🇳🇬", name: "Nigeria" },
    { code: "NI", flag: "🇳🇮", name: "Nikaragua" },
    { code: "NO", flag: "🇳🇴", name: "Norwegia" },
    { code: "NZ", flag: "🇳🇿", name: "Nowa Zelandia" },
    { code: "OM", flag: "🇴🇲", name: "Oman" },
    { code: "PK", flag: "🇵🇰", name: "Pakistan" },
    { code: "PW", flag: "🇵🇼", name: "Palau" },
    { code: "PA", flag: "🇵🇦", name: "Panama" },
    { code: "PG", flag: "🇵🇬", name: "Papua-Nowa Gwinea" },
    { code: "PY", flag: "🇵🇾", name: "Paragwaj" },
    { code: "PE", flag: "🇵🇪", name: "Peru" },
    { code: "PL", flag: "🇵🇱", name: "Polska" },
    { code: "PT", flag: "🇵🇹", name: "Portugalia" },
    { code: "CG", flag: "🇨🇬", name: "Republika Konga" },
    { code: "KR", flag: "🇰🇷", name: "Republika Korei" },
    { code: "MK", flag: "🇲🇰", name: "Republika Macedonii Północnej" },
    { code: "MD", flag: "🇲🇩", name: "Republika Mołdawii" },
    { code: "RO", flag: "🇷🇴", name: "Rumunia" },
    { code: "RW", flag: "🇷🇼", name: "Rwanda" },
    { code: "EH", flag: "🇪🇭", name: "Sahara Zachodnia" },
    { code: "KN", flag: "🇰🇳", name: "Saint Kitts i Nevis" },
    { code: "LC", flag: "🇱🇨", name: "Saint Lucia" },
    { code: "VC", flag: "🇻🇨", name: "Saint Vincent i Grenadyny" },
    { code: "SV", flag: "🇸🇻", name: "Salwador" },
    { code: "WS", flag: "🇼🇸", name: "Samoa" },
    { code: "SM", flag: "🇸🇲", name: "San Marino" },
    { code: "SN", flag: "🇸🇳", name: "Senegal" },
    { code: "RS", flag: "🇷🇸", name: "Serbia" },
    { code: "SC", flag: "🇸🇨", name: "Seszele" },
    { code: "SL", flag: "🇸🇱", name: "Sierra Leone" },
    { code: "SG", flag: "🇸🇬", name: "Singapur" },
    { code: "SK", flag: "🇸🇰", name: "Słowacja" },
    { code: "SI", flag: "🇸🇮", name: "Słowenia" },
    { code: "SO", flag: "🇸🇴", name: "Somalia" },
    { code: "SD", flag: "🇸🇩", name: "Sudan" },
    { code: "SS", flag: "🇸🇸", name: "Sudan Południowy" },
    { code: "SR", flag: "🇸🇷", name: "Surinam" },
    { code: "SY", flag: "🇸🇾", name: "Syria" },
    { code: "CH", flag: "🇨🇭", name: "Szwajcaria" },
    { code: "SE", flag: "🇸🇪", name: "Szwecja" },
    { code: "TJ", flag: "🇹🇯", name: "Tadżykistan" },
    { code: "TH", flag: "🇹🇭", name: "Tajlandia" },
    { code: "TZ", flag: "🇹🇿", name: "Tanzania" },
    { code: "TG", flag: "🇹🇬", name: "Togo" },
    { code: "TO", flag: "🇹🇴", name: "Tonga" },
    { code: "TT", flag: "🇹🇹", name: "Trynidad i Tobago" },
    { code: "TN", flag: "🇹🇳", name: "Tunezja" },
    { code: "TR", flag: "🇹🇷", name: "Turcja" },
    { code: "TM", flag: "🇹🇲", name: "Turkmenistan" },
    { code: "TV", flag: "🇹🇻", name: "Tuvalu" },
    { code: "UG", flag: "🇺🇬", name: "Uganda" },
    { code: "UA", flag: "🇺🇦", name: "Ukraina" },
    { code: "UY", flag: "🇺🇾", name: "Urugwaj" },
    { code: "UZ", flag: "🇺🇿", name: "Uzbekistan" },
    { code: "VU", flag: "🇻🇺", name: "Vanuatu" },
    { code: "VA", flag: "🇻🇦", name: "Watykan" },
    { code: "VE", flag: "🇻🇪", name: "Wenezuela" },
    { code: "HU", flag: "🇭🇺", name: "Węgry" },
    { code: "GB", flag: "🇬🇧", name: "Wielka Brytania" },
    { code: "VN", flag: "🇻🇳", name: "Wietnam" },
    { code: "IT", flag: "🇮🇹", name: "Włochy" },
    { code: "ZR", flag: "🇿🇲", name: "Zambia" },
    { code: "ZW", flag: "🇿🇼", name: "Zimbabwe" },
    { code: "AE", flag: "🇦🇪", name: "Zjednoczone Emiraty Arabskie" },
].sort((a, b) => a.name.localeCompare(b.name));
