interface Country {
    code: string;
    flag: string;
    name: string;
}

export const countries: Country[] = [
    { code: "US", flag: "🇺🇸", name: "Stany Zjednoczone" },
    { code: "GB", flag: "🇬🇧", name: "Wielka Brytania" },
    { code: "PL", flag: "🇵🇱", name: "Polska" },
    { code: "FI", flag: "🇫🇮", name: "Finlandia" },
    { code: "AF", flag: "🇦🇫", name: "Afganistan" },
    { code: "AL", flag: "🇦🇱", name: "Albania" },
    { code: "DZ", flag: "🇩🇿", name: "Algieria" },
    { code: "AD", flag: "🇦🇩", name: "Andora" },
    { code: "AO", flag: "🇦🇴", name: "Angola" },
    { code: "AR", flag: "🇦🇷", name: "Argentyna" },
    { code: "AM", flag: "🇦🇲", name: "Armenia" },
    { code: "AU", flag: "🇦🇺", name: "Australia" },
    { code: "AT", flag: "🇦🇹", name: "Austria" },
    { code: "AZ", flag: "🇦🇿", name: "Azerbejdżan" },
    { code: "BS", flag: "🇧🇸", name: "Bahamy" },
    { code: "BH", flag: "🇧🇭", name: "Bahrajn" },
    { code: "BD", flag: "🇧🇩", name: "Bangladesz" },
    { code: "BB", flag: "🇧🇧", name: "Barbados" },
    { code: "BE", flag: "🇧🇪", name: "Belgia" },
    { code: "BZ", flag: "🇧🇿", name: "Belize" },
    { code: "BJ", flag: "🇧🇯", name: "Benin" },
    { code: "BT", flag: "🇧🇹", name: "Bhutan" },
    { code: "BY", flag: "🇧🇾", name: "Białoruś" },
    { code: "BO", flag: "🇧🇴", name: "Boliwia" },
    { code: "BA", flag: "🇧🇦", name: "Bośnia i Hercegowina" },
    { code: "BW", flag: "🇧🇼", name: "Botswana" },
    { code: "BR", flag: "🇧🇷", name: "Brazylia" },
    { code: "BN", flag: "🇧🇳", name: "Brunei" },
    { code: "BG", flag: "🇧🇬", name: "Bułgaria" },
    { code: "BF", flag: "🇧🇫", name: "Burkina Faso" },
    { code: "BI", flag: "🇧🇮", name: "Burundi" },
    { code: "CL", flag: "🇨🇱", name: "Chile" },
    { code: "CN", flag: "🇨🇳", name: "Chiny" },
    { code: "HR", flag: "🇭🇷", name: "Chorwacja" },
    { code: "CY", flag: "🇨🇾", name: "Cypr" },
    { code: "TD", flag: "🇹🇩", name: "Czad" },
    { code: "ME", flag: "🇲🇪", name: "Czarnogóra" },
    { code: "CZ", flag: "🇨🇿", name: "Czechy" },
    { code: "DK", flag: "🇩🇰", name: "Dania" },
    { code: "DM", flag: "🇩🇲", name: "Dominika" },
    { code: "DO", flag: "🇩🇴", name: "Dominikana" },
    { code: "DJ", flag: "🇩🇯", name: "Dżibuti" },
    { code: "EG", flag: "🇪🇬", name: "Egipt" },
    { code: "EC", flag: "🇪🇨", name: "Ekwador" },
    { code: "ER", flag: "🇪🇷", name: "Erytrea" },
    { code: "EE", flag: "🇪🇪", name: "Estonia" },
    { code: "ET", flag: "🇪🇹", name: "Etiopia" },
    { code: "FJ", flag: "🇫🇯", name: "Fidżi" },
    { code: "PH", flag: "🇵🇭", name: "Filipiny" },
    { code: "FR", flag: "🇫🇷", name: "Francja" },
    { code: "GA", flag: "🇬🇦", name: "Gabon" },
    { code: "GM", flag: "🇬🇲", name: "Gambia" },
    { code: "GH", flag: "🇬🇭", name: "Ghana" },
    { code: "GR", flag: "🇬🇷", name: "Grecja" },
    { code: "GD", flag: "🇬🇩", name: "Grenada" },
    { code: "GE", flag: "🇬🇪", name: "Gruzja" },
    { code: "GY", flag: "🇬🇾", name: "Gujana" },
    { code: "GT", flag: "🇬🇹", name: "Gwatemala" },
    { code: "GN", flag: "🇬🇳", name: "Gwinea" },
    { code: "GW", flag: "🇬🇼", name: "Gwinea Bissau" },
    { code: "HT", flag: "🇭🇹", name: "Haiti" },
    { code: "ES", flag: "🇪🇸", name: "Hiszpania" },
    { code: "HN", flag: "🇭🇳", name: "Honduras" },
    { code: "IN", flag: "🇮🇳", name: "Indie" },
    { code: "ID", flag: "🇮🇩", name: "Indonezja" },
    { code: "IQ", flag: "🇮🇶", name: "Irak" },
    { code: "IR", flag: "🇮🇷", name: "Iran" },
    { code: "IE", flag: "🇮🇪", name: "Irlandia" },
    { code: "IS", flag: "🇮🇸", name: "Islandia" },
    { code: "IL", flag: "🇮🇱", name: "Izrael" },
    { code: "JM", flag: "🇯🇲", name: "Jamajka" },
    { code: "JP", flag: "🇯🇵", name: "Japonia" },
    { code: "YE", flag: "🇾🇪", name: "Jemen" },
    { code: "JO", flag: "🇯🇴", name: "Jordania" },
].sort((a, b) => a.name.localeCompare(b.name));
